import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { useParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

type ReportDetails = {
    applicationId: number;
    studentName: string;
    studentId: number;
    roomName: string | null;
    roomPrice: number;
    feePaid: boolean;
    status: string;
    roomId: number | null;
};

const FETCH_ALL_APPLICATIONS_API = `http://localhost:3000/api/hostels/all-applications`;

export default function StudentReportPage() {
    const { applicationId } = useParams();
    const [report, setReport] = useState<ReportDetails | null>(null);
    const [loading, setLoading] = useState(true);

    const parsedId = useMemo(() => Number(applicationId), [applicationId]);

    useEffect(() => {
        const fetchReport = async () => {
            if (!parsedId) {
                setLoading(false);
                return;
            }

            try {
                const response = await axios.get(FETCH_ALL_APPLICATIONS_API);
                const match = response.data.find(
                    (app: ReportDetails) => app.applicationId === parsedId
                );
                setReport(match || null);
            } catch (error) {
                console.error("Error fetching report:", error);
                setReport(null);
            } finally {
                setLoading(false);
            }
        };

        fetchReport();
    }, [parsedId]);

    const handlePrint = () => {
        window.print();
    };

    if (loading) {
        return <div className="page-shell page-enter">Loading report...</div>;
    }

    if (!report) {
        return (
            <div className="page-shell page-enter">
                <p className="mb-4">Report not found.</p>
                <Link to="/reports" className="text-blue-600 underline">Back to Reports</Link>
            </div>
        );
    }

    return (
        <div className="page-shell page-enter">
            <div className="page-header print:hidden">
                <div>
                    <h2 className="page-title">Student Statement</h2>
                    <p className="page-subtitle">Official record for hostel assignment and fee status.</p>
                </div>
                <Button
                    className="border-transparent text-white bg-[var(--accent)] hover:bg-[var(--accent-strong)] cursor-pointer"
                    onClick={handlePrint}
                >
                    Print / Save as PDF
                </Button>
            </div>

            <div className="print-statement max-w-3xl mx-auto panel p-6 print:shadow-none print:border-0">
                <div className="flex justify-between items-center border-b border-gray-200 pb-4 mb-6">
                    <div>
                        <h1 className="text-2xl font-semibold text-gray-900">Official Student Statement</h1>
                        <p className="text-sm text-gray-500">Hostel Management System</p>
                    </div>
                    <div className="text-right text-xs text-gray-400">
                        <div>Document ID</div>
                        <div>HM-{report.applicationId}</div>
                    </div>
                </div>

                <div className="grid gap-4 text-gray-800">
                    <div className="flex justify-between border border-gray-100 rounded-xl px-4 py-3">
                        <span className="font-medium text-gray-600">Student Name</span>
                        <span>{report.studentName}</span>
                    </div>
                    <div className="flex justify-between border border-gray-100 rounded-xl px-4 py-3">
                        <span className="font-medium text-gray-600">Student ID</span>
                        <span>{report.studentId}</span>
                    </div>
                    <div className="flex justify-between border border-gray-100 rounded-xl px-4 py-3">
                        <span className="font-medium text-gray-600">Assigned Room</span>
                        <span>{report.roomName || "Not Assigned"}</span>
                    </div>
                    <div className="flex justify-between border border-gray-100 rounded-xl px-4 py-3">
                        <span className="font-medium text-gray-600">Room Fee</span>
                        <span>{report.roomPrice}</span>
                    </div>
                    <div className="flex justify-between border border-gray-100 rounded-xl px-4 py-3">
                        <span className="font-medium text-gray-600">Payment Status</span>
                        <span className={`pill ${report.feePaid ? "pill--paid" : "pill--unpaid"}`}>
                            {report.feePaid ? "Paid" : "Unpaid"}
                        </span>
                    </div>
                </div>

                <div className="mt-8 text-sm text-gray-500">
                    This statement is generated by the hostel administration and reflects the latest recorded fee status.
                </div>
            </div>

            <div className="mt-6 text-center print:hidden">
                <Link to="/reports" className="text-blue-600 underline">Back to Reports</Link>
            </div>
        </div>
    );
}
