import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { useParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

type ReportDetails = {
    applicationId: number;
    studentName: string;
    studentId: number;
    roomName: string | null;
    roomPrice: number;
    feePaid: boolean;
    status: string;
    roomId: number | null;
};

const FETCH_ALL_APPLICATIONS_API = `http://localhost:3000/api/hostels/all-applications`;

export default function StudentReportPage() {
    const { applicationId } = useParams();
    const [report, setReport] = useState<ReportDetails | null>(null);
    const [loading, setLoading] = useState(true);

    const parsedId = useMemo(() => Number(applicationId), [applicationId]);

    useEffect(() => {
        const fetchReport = async () => {
            if (!parsedId) {
                setLoading(false);
                return;
            }

            try {
                const response = await axios.get(FETCH_ALL_APPLICATIONS_API);
                const match = response.data.find(
                    (app: ReportDetails) => app.applicationId === parsedId
                );
                setReport(match || null);
            } catch (error) {
                console.error("Error fetching report:", error);
                setReport(null);
            } finally {
                setLoading(false);
            }
        };

        fetchReport();
    }, [parsedId]);

    const handlePrint = () => {
        window.print();
    };

    if (loading) {
        return <div className="p-6">Loading report...</div>;
    }

    if (!report) {
        return (
            <div className="p-6">
                <p className="mb-4">Report not found.</p>
                <Link to="/reports" className="text-blue-600 underline">Back to Reports</Link>
            </div>
        );
    }

    return (
        <div className="p-6">
            <div className="flex justify-between items-center mb-6 print:hidden max-w-3xl mx-auto">
                <Link to="/reports" className="text-blue-600 underline">Back to Reports</Link>
                <Button
                    className="border-gray-800 text-white bg-gray-900 hover:bg-gray-800 cursor-pointer"
                    onClick={handlePrint}
                >
                    Print / Save as PDF
                </Button>
            </div>

            <div className="print-statement max-w-3xl mx-auto bg-white border border-gray-200 shadow-sm print:shadow-none print:border-0 p-5">
                <div className="border-b border-gray-200 pb-4 mb-6">
                    <h1 className="text-2xl font-semibold text-gray-900">Official Student Statement</h1>
                    <p className="text-sm text-gray-500">Hostel Management System</p>
                </div>

                <div className="space-y-4 text-gray-800">
                    <div className="flex justify-between">
                        <span className="font-medium">Student Name</span>
                        <span>{report.studentName}</span>
                    </div>
                    <div className="flex justify-between">
                        <span className="font-medium">Student ID</span>
                        <span>{report.studentId}</span>
                    </div>
                    <div className="flex justify-between">
                        <span className="font-medium">Assigned Room</span>
                        <span>{report.roomName || "Not Assigned"}</span>
                    </div>
                    <div className="flex justify-between">
                        <span className="font-medium">Room Fee</span>
                        <span>{report.roomPrice}</span>
                    </div>
                    <div className="flex justify-between">
                        <span className="font-medium">Payment Status</span>
                        <span>{report.feePaid ? "Paid" : "Unpaid"}</span>
                    </div>
                </div>

                <div className="mt-8 text-sm text-gray-500">
                    This statement is generated by the hostel administration and reflects the latest recorded fee status.
                </div>
            </div>
        </div>
    );
}
